name: DriftBuddy Security Scan

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  security-scan:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: Install KICS
      run: |
        curl -L https://github.com/Checkmarx/kics/releases/latest/download/kics_linux_amd64.tar.gz -o kics.tar.gz
        tar -xzf kics.tar.gz
        sudo mv kics /usr/local/bin/
        sudo chmod +x /usr/local/bin/kics
        rm kics.tar.gz
        
    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install openai python-dotenv markdown
        
    - name: Set up OpenAI API Key
      run: |
        echo "OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }}" >> $GITHUB_ENV
        
    - name: Run DriftBuddy Security Scan
      run: |
        python driftbuddy.py . --all --reports-dir ./security-reports
        
    - name: Upload Security Reports
      uses: actions/upload-artifact@v4
      with:
        name: driftbuddy-security-reports
        path: security-reports/
        retention-days: 30 