name: DriftBuddy Basic Security Scan

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  security-scan:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.22'

    - name: Install KICS from source
      run: |
        # Clone KICS repository
        git clone https://github.com/Checkmarx/kics.git
        cd kics

        # Install Go dependencies and build
        go mod vendor
        go build -o ./bin/kics cmd/console/main.go

        # Install KICS globally
        sudo mv ./bin/kics /usr/local/bin/
        sudo chmod +x /usr/local/bin/kics

        # Clean up
        cd ..
        rm -rf kics

        # Verify installation
        kics version

    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Set up OpenAI API Key
      run: |
        echo "OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }}" >> $GITHUB_ENV

    - name: Run DriftBuddy Security Scan
      run: |
        python driftbuddy.py . --all --reports-dir ./security-reports

    - name: Upload Security Reports
      uses: actions/upload-artifact@v4
      with:
        name: driftbuddy-security-reports
        path: security-reports/
        retention-days: 30
